/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
 * Generated on: 18-Mar-2025 14:07:00
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 102
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /cad/matlab/matlab2023b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int BL = 102;
const int32_T B[102] = {
       -515860,    -2018687,    -5362055,   -11603411,   -21565046,   -35686216,
     -53391945,   -73016489,   -91589053,  -105383425,  -110503938,  -104071341,
     -85106985,   -55386511,   -19394114,    16263560,    44412288,    59059851,
      57255182,    40094432,    12808605,   -16548769,   -39239822,   -48499961,
     -41634426,   -21072786,     6284126,    31124103,    44802172,    42279435,
      24077016,    -3663544,   -31021587,   -47672121,   -46588404,   -26900426,
       5290124,    38504411,    59634059,    58627446,    32633810,   -11961939,
     -60449778,   -93673757,   -93794353,   -50239678,    36110148,   151932119,
     274204040,   376007135,   433764903,   433764903,   376007135,   274204040,
     151932119,    36110148,   -50239678,   -93794353,   -93673757,   -60449778,
     -11961939,    32633810,    58627446,    59634059,    38504411,     5290124,
     -26900426,   -46588404,   -47672121,   -31021587,    -3663544,    24077016,
      42279435,    44802172,    31124103,     6284126,   -21072786,   -41634426,
     -48499961,   -39239822,   -16548769,    12808605,    40094432,    57255182,
      59059851,    44412288,    16263560,   -19394114,   -55386511,   -85106985,
    -104071341,  -110503938,  -105383425,   -91589053,   -73016489,   -53391945,
     -35686216,   -21565046,   -11603411,    -5362055,    -2018687,     -515860
};
